<div class="sidebar-overlay"></div>
<div class="sidebar-toggle custom-sidebar-toggle"><i class="fas fa-sliders-h"></i></div>
<aside class="sidebar-home col-lg-3 order-lg-first mobile-sidebar">
<div class="side-menu-wrapper text-uppercase mb-2 d-none d-lg-block">
    <h2 class="side-menu-title bg-gray ls-n-25">Browse Categories</h2>

    <nav class="side-nav">
        <ul class="menu menu-vertical sf-arrows">
            <li class="active"><a href="index.php"><i class="icon-home"></i>Home</a></li>
        </ul>
    </nav>
</div>
<!-- End .side-menu-container -->

<div class="widget widget-banners px-3 pb-3 text-center">
    <div class="owl-carousel owl-theme dots-small">
        <div class="banner d-flex flex-column align-items-center">
            <h3 class="badge-sale bg-primary d-flex flex-column align-items-center justify-content-center text-uppercase">
                <em>Sale</em>Many Item
            </h3>

            <h4 class="sale-text text-uppercase"><small>UP
                    TO</small>50<sup>%</sup><sub>off</sub></h4>
            <p>For pre-ordered goods</p>
            <a href="demo1-shop.html" class="btn btn-dark btn-md">View Sale</a>
        </div>
        <!-- End .banner -->

        <div class="banner banner4">
            <figure>
                <img src="assets/images/demoes/demo1/banners/banner-7.jpg" alt="banner">
            </figure>

            <div class="banner-layer">
                <div class="coupon-sale-content">
                    <h4>DRONE + CAMERAS</h4>
                    <h5 class="coupon-sale-text text-gray ls-n-10 p-0 font1"><i>UP
                            TO</i><b class="text-white bg-dark font1">$100</b> OFF</h5>
                    <p class="ls-0">Top Brands and Models!</p>
                    <a href="demo1-shop.html" class="btn btn-inline-block btn-dark btn-black ls-0">VIEW
                        SALE</a>
                </div>
            </div>
        </div>
        <!-- End .banner -->

        <div class="banner banner5">
            <h4>HEADPHONES SALE</h4>

            <figure class="m-b-3">
                <img src="assets/images/demoes/demo1/banners/banner-8.jpg" alt="banner">
            </figure>

            <div class="banner-layer">
                <div class="coupon-sale-content">
                    <h5 class="coupon-sale-text ls-n-10 p-0 font1"><i>UP
                            TO</i><b class="text-white bg-secondary font1">50%</b> OFF</h5>
                    <a href="demo1-shop.html" class="btn btn-inline-block btn-dark btn-black ls-0">VIEW
                        SALE</a>
                </div>
            </div>
        </div>
        <!-- End .banner -->
    </div>
    <!-- End .banner-slider -->
</div>
<!-- End .widget -->

<div class="widget widget-newsletters bg-gray text-center">
    <h3 class="widget-title text-uppercase m-b-3">Subscribe Newsletter</h3>
    <p class="mb-2">Get all the latest information on Events, Sales and Offers. </p>
    <form action="#">
        <div class="form-group position-relative sicon-envolope-letter">
            <input type="email" class="form-control" name="newsletter-email" placeholder="Email address">
        </div>
        <!-- Endd .form-group -->
        <input type="submit" class="btn btn-primary btn-md" value="Subscribe">
    </form>
</div>
<!-- End .widget -->

<div class="widget widget-testimonials">
    <div class="owl-carousel owl-theme dots-left dots-small">
        <div class="testimonial">
            <div class="testimonial-owner">
                <figure>
                    <img src="assets/images/ceo.jpg" alt="client">
                </figure>

                <div>
                    <h4 class="testimonial-title">Aku sunshine</h4>
                    <span>CEO &amp; Founder</span>
                </div>
            </div>
            <!-- End .testimonial-owner -->

            <blockquote class="ml-4 pr-0">
                <p> "without water on earth we won't survive this far"
                </p>
            </blockquote>
        </div>
        <!-- End .testimonial -->

        <div class="testimonial">
            <div class="testimonial-owner">
                <figure>
                    <img src="assets/images/clients/client-2.jpg" alt="client">
                </figure>

                <div>
                    <h4 class="testimonial-title">Dae Smith</h4>
                    <span>CEO &amp; Founder</span>
                </div>
            </div>
            <!-- End .testimonial-owner -->

            <blockquote class="ml-4 pr-0">
                <p>Lorem ipsum dolor sit amet, consectetur elitad adipiscing Cras non placerat mi.
                </p>
            </blockquote>
        </div>
        <!-- End .testimonial -->

        <div class="testimonial">
            <div class="testimonial-owner">
                <figure>
                    <img src="assets/images/clients/client-3.jpg" alt="client">
                </figure>

                <div>
                    <h4 class="testimonial-title">John Doe</h4>
                    <span>CEO &amp; Founder</span>
                </div>
            </div>
            <!-- End .testimonial-owner -->

            <blockquote class="ml-4 pr-0">
                <p>Lorem ipsum dolor sit amet, consectetur elitad adipiscing Cras non placerat mi.
                </p>
            </blockquote>
        </div>
        <!-- End .testimonial -->
    </div>
    <!-- End .testimonials-slider -->
</div>
<!-- End .widget -->


<!-- End .widget -->
</aside>